min_n_samples: 1000
scale_n_samples: 100
preconditioner: True
sr_diag_shift: 1e-2
tr_learning: False
noise_scale: 0.1
callbacks: [variance]
preconditioner_operator: exact
preconditioner_operator_eps: 1e-2